### ISSUE TITLE
GCC 7.3.1 and 8.3.1 emit undefined reference to inline functions. But GCC 4.8.5 works fine 

### ISSUE THREAD

**Issue by LyleLee** [hisilicon/centos-kunpeng-issue#5]
***Describe the bug***
I am compile the following code:
```
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>

inline int64_t Now() {
#if __i386__
        int64_t ret;
        __asm__ volatile("rdtsc" : "=A"(ret));
        return ret;
#elif __x86_64__
        uint64_t low, high;
        __asm__ volatile("rdtsc" : "=a"(low), "=d"(high));
        return (high << 32) | low;

#elif __aarch64__
        int64_t virtual_timer_value;
        asm volatile("mrs %0, cntvct_el0" : "=r"(virtual_timer_value));
        return virtual_timer_value;
#else
#endif
}

int main()
{
        int64_t t1 = Now();
        sleep(1);
        int64_t t2 = Now();

        printf("t1:%ld, t2:%ld, t2-t1:%ld\n",t1,t2,(t2-t1)/1000000);

        return 0;
}
```
```
gcc benchmark_cycle.c
```
I have the following output with GCC 7.3.1 and 8.3.1 on CentOS:
```
[user@centos rdt]$ gcc benchmark_cycle.c
/tmp/cc2RtZTI.o: In function `main':
benchmark_cycle.c:(.text+0x8): undefined reference to `Now'
benchmark_cycle.c:(.text+0x18): undefined reference to `Now'
collect2: error: ld returned 1 exit status
```
But everthing work fine with GCC 4.8.5
```
[user@centos rdt]$ gcc benchmark_cycle.c
user@centos rdt]$
```

***version info (please complete the following information):***
 - OS: CentOS7.6 
 - Kernel Version: 4.14.0-115.el7a.0.1.aarch64115.el7a.0.1.aarch64]
 - GCC 7.3.1 GCC 8.3.1
***To Reproduce***
1. compile the code to have the behavior
```
gcc benchmark_cycle.c
```

***Expected behavior***
All GCC should support inline functions. if not, show have documentation about it.

**Comment by xin3liang** [comment]
Solution
------------
Add -fgnu89-inline gcc option
See bellow Links for more explanations :
http://wangcong.org/2012/03/07/-e5-85-b3-e4-ba-8e-extern-inline/ 
https://gcc.gnu.org/onlinedocs/gcc/Inline.html

**Comment by LyleLee** [comment]
ok, that works for me
